apiVersion: v1
kind: Service
metadata:
  name: "blog-project"
  namespace: "blog-test"
  labels:
    name: "blog-project"
spec:
  type: "NodePort"
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: "blog-project"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "blog-project"
  namespace: "blog-test"
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 1
  selector:
    matchLabels:
      app: "blog-project"
  template:
    metadata:
      labels:
        app: "blog-project"
        applicationtype: "backend"
        devlanguages: "csharp"
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: worker
                operator: In
                values:
                - "true"
      containers:
      - env:
        - name: ASPNETCORE_ENVIRONMENT
          value: test
        image: "hqharbor.lcwaikiki.com/mym/blog-project-test:__DOCKERIMGVER__"
        imagePullPolicy: Always
        name: "blog-project"
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "3072Mi"
            cpu: "2000m"
      imagePullSecrets:
        - name: csregistry
      restartPolicy: Always